import {
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Cake,
  Car,
  ChartLine,
  ChartPie,
  CircleHelp,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Handshake,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Music,
  PawPrint,
  Percent,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  Train,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/*
 * A curated registry rather than lucide's full export map: importing all 6000+
 * icons to resolve a handful of names would dominate the bundle, and a picker
 * is more useful with a considered set than with everything.
 */
export const ICONS = {
  wallet: Wallet,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  banknote: Banknote,
  'credit-card': CreditCard,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  percent: Percent,
  receipt: Receipt,
  tag: Tag,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  house: House,
  utensils: Utensils,
  coffee: Coffee,
  cake: Cake,
  bus: Bus,
  train: Train,
  car: Car,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  zap: Zap,
  wifi: Wifi,
  lightbulb: Lightbulb,
  repeat: Repeat,
  smartphone: Smartphone,
  laptop: Laptop,
  briefcase: Briefcase,
  handshake: Handshake,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  scissors: Scissors,
  shirt: Shirt,
  gift: Gift,
  music: Music,
  clapperboard: Clapperboard,
  gamepad: Gamepad2,
  'paw-print': PawPrint,
  leaf: Leaf,
  sparkles: Sparkles,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) return CircleHelp
  return ICONS[name as IconName] ?? CircleHelp
}
