/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./server/env.d.ts` (hash: b30519c6174baafd973f4ffc74f0d816)
interface __BaseEnv_Env {
	DB: D1Database;
	PAGES_ORIGIN: "https://your-project.pages.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PAGES_ORIGIN">> {}
}
